### ISSUE TITLE
Enveloped signature is invalid

### ISSUE THREAD

**Issue by shunkica** [eclipse-ee4j/metro-jax-ws#93] opened 2019-12-09 12:28 UTC
I am sorry if this is not the correct place for this report.

I am trying to upgrade a project from Java 8 to Java 13. The project uses the Java EE modules that have been removed from Java11+ so I imported jaxws from maven.

        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>2.3.3-b01</version>
        </dependency>

This is what the signed message structure needs to look like:

    ...
    <SOAP-ENV:Body>
      <MyElement Id="signThisElement">
        <child1></child1>
        <child2></child2>
        <Signature>
          ...
        </Signature>
      </MyElement>
    </SOAP-ENV:Body>
    ...

The problem is that, with the exact same code and the exact same message, jaxws in Java 13 produces a different signature than Java 8 does.

Specifically there are two differences:
- DigestValue and SignatureValue element values are completely different
- SignatureValue and X509Certificate have carriage return encoded as XML character reference at the end of every line (`&#13;`)

To sign the SOAP message I do the following:

    SOAPBody soapBody = soapMessage.getSOAPBody();
    Node nodeToSign = soapBody.getFirstChild(); // I actually use xpath to select this
    // then i set the attribute id node, signature, keys,
    // transforms (including Transform.ENVELOPED), reference etc.
    ...
    // finally to configure context
    DOMSignContext dsc = new DOMSignContext(privateKey, nodeToSign);
    
The structure of the message produced by this code in Java13 is exactly the same as in Java8, but a diff between the two messages shows that the DigestValue and SignatureValue element values are different, and also in Java13 (and 11) SignatureValue and X509Certificate have `&#13;` appended to the end of each line, while this is not present in the signature generated by Java 8.

I did some experimenting, and if I pass the `soapBody` directly to `DOMSignContext` instead of `nodeToSign` (without making any other changes), then the generated DigestValue and SignatureValue objects are valid (they have the same values Java8 produces when `nodeToSign` is passed to dsc)  - BUT the structure of the xml is invalid because the`Signature` element gets appended as a sibling of `MyElement` instead of being appended as a last child, like this:

    ...
    <SOAP-ENV:Body>
      <MyElement Id="signThisElement">
        <child1></child1>
        <child2></child2>
      </MyElement>
      <Signature>
        ...
      </Signature>
    </SOAP-ENV:Body>
    ...

I have tested this on both of the latest versions of AdoptOpenJDK 11 and 13.

There was a similar bug reported here but this was for an Enveloping signature, instead of Enveloped, and it has been marked resolved in March: [bug report][1]

Here is the entire code I use for signing the SOAPMessage: [signSOAP][2]

  [1]: https://bugs.openjdk.java.net/browse/JDK-8217878
  [2]: https://gist.github.com/shunkica/ab3674e0161c7c1efac1854299813c94

**Comment by lukasj** [comment] 2019-12-09 12:58
There is a change in Base64 encoder/decoder in JDK in how it handles line endings. Can you try to set `-Dorg.apache.xml.security.ignoreLineBreaks=true`?

**Comment by shunkica** [comment] 2019-12-09 13:10
> There is a change in Base64 encoder/decoder in JDK in how it handles line endings. Can you try to set `-Dorg.apache.xml.security.ignoreLineBreaks=true`?

I have added this option and it produces the same result as without the option.
The SignatureValue and DigestValue element values are the same and `&#13;` is still present at the end of each line in SignatureValue and X509Certificate.

**Comment by shunkica** [comment] 2019-12-09 19:52
> 
> 
> There is a change in Base64 encoder/decoder in JDK in how it handles line endings. Can you try to set `-Dorg.apache.xml.security.ignoreLineBreaks=true`?

Using the property you suggested made no difference.

I also tried this property: `-Dcom.sun.org.apache.xml.internal.security.ignoreLineBreaks=true`
This one removed all the line breaks (and with them the `&#13;` characters) starting from the signature element until the end of the soap message. Unfortunately the produced signature is also invalid.

**Comment by shunkica** [comment] 2019-12-09 21:43
I ran multiple tests with jdk8, jdk11, and jdk13 (all latest version of AdoptOpenJDK).
I also tested setting ignoreLineBreaks on org.apache.xml.security vs com.sun.org.apache.xml.internal.security vs not setting any property.

Here are my observations:
 - setting ignoreLineBreaks on the org.apache.xml.security did not work on any of the tested JDK versions
 - setting ignoreLineBreaks on the com.sun.org.apache.xml.internal.security worked on all of the tested versions
 - Java 11 and Java 13 behave the same way

To stay brief I will only paste the DigestValues here.
The correct DigestValue for the message is only present on Java8.

Java 8 with no parameter
DigestValue - NuCdkvEe/d/CraL4euO12iOV6l8=

Java 8 with com.sun.* property
DigestValue - NuCdkvEe/d/CraL4euO12iOV6l8=

Java 8 with org.apache.* property
DigestValue - NuCdkvEe/d/CraL4euO12iOV6l8=

Java 11 with no parameter
DigestValue - x6cC45lHsoESckUIYpnd+xoSzy4=

Java 11 with com.sun.* property
DigestValue - B/iFVo+ZTIKk5iMqGFvht0wODXc=

Java 11 with org.apache.* property
DigestValue - x6cC45lHsoESckUIYpnd+xoSzy4=

Java 13 with no parameter
DigestValue - x6cC45lHsoESckUIYpnd+xoSzy4=

Java 13 with com.sun.* property
DigestValue - B/iFVo+ZTIKk5iMqGFvht0wODXc=

Java 13 with org.apache.* property
DigestValue - x6cC45lHsoESckUIYpnd+xoSzy4=

Putting all this aside, I think the key here is not in the line breaks.
Why would Java 13 produce the correct DigestValue when the parent of the node to be signed is passed to DOMSignContext?

Here is the DigestValue for Java13 when the SOAPBody is passed to DOMSignContext, instead of the Node that is to be signed:

Java 13 with no parameter - soapbody passed
DigestValue - NuCdkvEe/d/CraL4euO12iOV6l8=

Java 13 with com.sun.* property - soapbody passed
DigestValue - NuCdkvEe/d/CraL4euO12iOV6l8=

So we see now the DigestValue is correct for the message.
If I pass the SOAPBody to DOMSignContext then the Signature is placed as the last child of the body,
and I need it to be placed as the list child of the element that is being signed like it does on Java 8 when nodeToBeSigned is passed (Enveloped).

This made me feel I could create a valid message signature if I passed the SOAPBody to DOMSignContext, and then somehow move the signature into the first child of the SOAPBody.

So I did that by adding this after signature.sign(dsc):
    Node sigNode = soapMessage.getSOAPBody().getLastChild();
    soapMessage.getSOAPBody().getFirstChild().appendChild(sigNode);

And suddenly the signature is now valid. Even the signature with &#13; is valid, and the remote server confirms it.
This definitely feels like a regression.

**Comment by lukasj** [comment] 2019-12-09 23:07
Behaviour changed in jdk 8 update 231, see its release notes:  https://www.oracle.com/technetwork/java/javase/8u231-relnotes-5592812.html

**Comment by shunkica** [comment] 2019-12-09 23:16
The tests I have done on Java 8 were on 8u2.3.2 and the old code works there, and I know for a fact that it works on older versions of 8 so I don't think that it is related.

**Comment by lukasj** [comment] 2019-12-09 23:46
Changes like https://issues.apache.org/jira/browse/SANTUARIO-482 and related are in JDK 8 since update 231 - as noted in release notes; previous version of xmlsec library in jdk was 1.5.4. Why do you think they are not related?

**Comment by shunkica** [comment] 2019-12-10 00:09
Because I have already determined in my previous comment that the newline character has nothing to do with the fact the signature is invalid. And the remote server even recognozes the valid signature if it contains the newline reference.
The difference is in the interaction of DOMSignContext and XMLSignature as seen on the gist I posted.
The same code produces two completely different signatures on Java 8 and Java 11+ with jaxws-rt. Java 11+ produces the same result after applying the fix from gist, and the ignoreLineBreaks property does not have to be set for the signature to be valid.

I think the issue can be reproduced by the code sample provided, but if I am missing something obvious please let me know.

**Comment by shunkica** [comment] 2019-12-11 01:19
I spent a few hours in the debugger and I tracked down the issue to com.sun.org.apache.xml.internal.security.c14n.implementation.CanonicalizerBase, specifically the  canonicalizeSubTree(Node currentNode, NameSpaceSymbTable ns, Node endnode, int documentLevel) method.
For some reason this method in Java 11+ canonicalizes the Signature element as well, even though that is against enveloped signature spec. This makes the whole signature invalid.
I don't have time right now to dig deeper than that but if it is not related to jaxws you can close this issue.

**Comment by coheigea** [comment] 2020-01-03 17:32
@shunkica I've added a simple test-case to my github repo to reproduce the issue referenced in SANTUARIO-516

https://github.com/coheigea/testcases/tree/master/misc/saaj

The XML Signature validation failure is caused by the fact that the owner document of the URI attribute in the document does not equal the owner document of the element the owner belongs to. I'm pretty sure this is a bug in SAAJ.

Note that if you use 2.2.10, then it works fine.

**Comment by faridadh** [comment] 2020-02-03 18:21
Hi everyone, 

I am facing similar issue and it is blocking the migration to Java 11. Is there a timeline for fixing this issue or a suggested work around for fixing it?

**Comment by shunkica** [comment] 2020-02-04 00:28
> Hi everyone,
> 
> I am facing similar issue and it is blocking the migration to Java 11. Is there a timeline for fixing this issue or a suggested work around for fixing it?

You can pass the parent of the node you want signed to DOMSignContext and then move the signature once it is generated. Look at the gist I provided in one of my previous comments.

**Comment by faridadh** [comment] 2020-02-04 21:56
I tried that approach earlier, but did not work and validation failed. I believe the reason for that is I am signing the whole envelope, so even if I move the signature element to the top level, it is still inside the signing content and because of the issue mentioned in https://github.com/eclipse-ee4j/metro-jax-ws/issues/93#issuecomment-564333970 , it affect the signature.

**Comment by faridadh** [comment] 2020-02-06 03:19
Not sure if that helps, 1.3.28 version is working and 1.4.0 is failing. So the changes between those releases cause the issue.

**Comment by brodziakm** [comment] 2020-09-01 23:46
Hi all,

I raised this issue under https://github.com/eclipse-ee4j/metro-saaj/issues/165. 

I have prepared a candidate fix that is enough to resolve correct canonicalization and signing under dsig and Santuario.

**Comment by aarowman** [comment] 2020-12-08 21:30
Are there any updates on this? The other linked issue has been closed

**Comment by lukasj** [comment] 2020-12-08 21:39
do you see the same problem in metro 3.0.0?

**Comment by shunkica** [comment] 2020-12-08 21:39
> 
> 
> Are there any updates on this? The other linked issue has been closed

I didn't test it but according to the commits it looks like this has been fixed in 3.0.0

**Comment by lukasj** [comment] 2020-12-08 22:00
so let's close this for now. Feel free to reopen or open new issue if see the problem there. Thanks!

**Closed by lukasj** 2020-12-08 22:00 UTC

**Comment by coheigea** [comment] 2020-12-09 07:30
I confirm my testcase works correctly with:

<groupId>com.sun.xml.ws</groupId>
<artifactId>jaxws-rt</artifactId>
<version>3.0.0</version>

**Comment by lukasj** [comment] 2021-01-04 18:44
Thank you for verification, @coheigea !

**Comment by lukebex3** [comment] 2022-03-25 04:05
@lukasj Re metro: It seems above the fix has been applied to metro 3x. What about later 2x versions?
I note metro 3 is based on jakarta servlet 5.0 which doesn't play nicely with tomcat < 10.
